# Generated by Django 3.2.7 on 2021-09-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='reserved_by',
            new_name='user',
        ),
    ]
