# Generated by Django 3.2.7 on 2021-09-05 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0005_roomreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='organizer',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('taken', 'Taken')], default='Taken', max_length=5),
        ),
    ]
